package me.or.royals;

public enum Achivments {

	
	RecentWolfKiller, OVOWINNER, FIRSTJOIN, ODINPIXELKILLER, FIRSTBUY,DONATOR,POSEIDON,RUSHER,UNSTOPABLE,UNBELIEVEABLE,IMMORTAL,UNLOCK_EM_ALL,ZEUS, SWAG, AMA_TUTRLE,GOD_OF_WAR, AIRBONE, MARKSMAN,SOUP_MASTER
}
