package me.or.royals;

public enum KitType {

	ENDERARCHER, WARTH, GANGSTER, GHAST, VAMPIRE, GROOPY, MINION, SPIDER, SMASHER, CREEPER, TROLLER,ARCHER,KNIGHT, RABBIT, BATMAN, GRAPPLER, KANGAROO, FISHER, HULK
}
